// reactjs/davidwhitcome.com/src/hero-header/hero-header.tsx
import React from 'react'
import './hero-header.scss'

interface IState {
  name: string,
  tag: string,
}

export default class HeroHeader extends React.Component<{}, IState> {
  state = {
    name: "David Whitcome",
    tag: "Software Developer"
  };

  constructor(props: {}) {
    super(props);
    this.ParallaxAnimation(); // Set header background to correct position for some browsers.
    window.addEventListener('scroll', this.ParallaxAnimation);
  }

  render = () => (
    <div id="header">
      <div id="header-background-wrapper">
        <div id="header-background"></div>
      </div>
      <div className="ie10-fix">
        <div id="header-centered">
          <h1>{this.state.name}</h1>
          <h2>{this.state.tag}</h2>
        </div>
      </div>
    </div>
  );

  ParallaxAnimation() {
    var headerBackground = document.getElementById("header-background-wrapper");
    if (headerBackground != null) {
      var backgroundPosition: number = window.pageYOffset / 4;
      if (backgroundPosition >= 0)
        headerBackground.style.marginTop = backgroundPosition + "px";
      else
        headerBackground.style.marginTop = "0px";
    }
  }
};

// src/app/hero-header/hero-header.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

@Component({
  selector: 'app-hero-header',
  templateUrl: './hero-header.component.pug',
  styleUrls: ['./hero-header.component.scss']
})
export class HeroHeaderComponent implements OnInit {
  Name: string = "David Whitcome";
  Tag: string = "Software Developer";
  header: HTMLElement;

  constructor() {
    window.addEventListener('scroll', this.ParallaxAnimation);
  }

  ngOnInit() {
    this.header = document.getElementById("header");
    this.ParallaxAnimation(); // Set header background to correct position for some browsers.
  }

  ParallaxAnimation() {
    if (parseInt(this.header.style.height) >= 80)
      this.header.style.height = (600 - window.pageYOffset) + "px";
    else
      this.header.style.height = "80px";

    document.getElementById("header-background").style.opacity = (1 - window.pageYOffset/600).toString();
    document.getElementById("header-bottom").style.opacity = (1 - window.pageYOffset/450).toString();
  }
}
